name: Merge upstream branches
on:
  schedule:
    - cron:  '0 13 * * *'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'Maseshi'
          git config --global user.email 'dermhioasw123@gmail.com'

          git pull --unshallow

          git remote add upstream https://github.com/AUTOMATIC1111/stable-diffusion-webui.git
          git fetch upstream

          git checkout master
          git merge --no-edit upstream/master
          git push origin master
